### PR TITLE
Refactor to use Functional Components, Query mods via search bar, Sort mods

### PR DESCRIPTION
**Pull request by bdlm-dev**
- Class-based components (deprecated) replaced by functional components & equivalent hooks
- Search bar queries against mod names, author names, and descriptions
- Mods can be sorted by the following, ascending and descending:
  - Mod Name
  - Author Name
  - Downloads
  - Latest Update
  - Release Date

image

### CODE REVIEW

**Comment by bdlm-dev** [comment]
Apologies the PR is quite large, the bulk of it has little to no functional changes though definitely worth a test on other machines to make sure everything works.

**Comment by xen-42** [comment]
- [x] Comparing new version (left) to old (right) we no longer have this message if all mods are installed
image

- [x] I'm also thinking that sorting options besides Default ought to ignore enabled and be consistent across all the mods. Same with forcing Winch to be at the top, should keep that only in Default sorting.

image

- [x] I think this X (above) should only apply to the search bar and not the sorting choice.
edit: Seeing as it didnt apply to the search bar I just moved it to the right of the sorting setting

- [x] Just for more clarity I think we should write "Sort by:" beside the sorting dropdown.

- [x] Default should also be alphabetical at this point (think its still download count)


These other points aren't necessarily changes to the PR but just things I thought of while reviewing it (more a todo list for myself):

- [x] We should also expose the latest update and release info in the expanded info for each mod, since we can sort using that but then dont actually know what the dates are for anything.

- [x] I think the description line should be displayed even when the mod row isn't expanded

Could try and add thumbnails to the mods list
edit: not going to do this last one because there's not enough space, would have to reorganize the left column

**Review by xen-42 — APPROVED** [review]

**Comment by MegaPiggy** [comment]
lgtm!
I think it'd be nice if there was a way to set the default sort in settings.

side by side changes
Installed
Available
Settings

**Review by MegaPiggy — APPROVED** [review]

**Comment by xen-42** [comment]
didnt realize the "winch modloader settings" header vanished, i'll probably add that back then merge

**Pull request merged**
